project("LibWindowsNative")
  targetname("Windows-Native") 
  kind("StaticLib")
  language("C")
  nativewchar("Off")
  exceptionhandling("Off")
  floatingpointexceptions("Off")
  intrinsics("on")
  flags({
    "NoBufferSecurityCheck"
  })
  includedirs({
    ".",
  })
  files({
    "**.hint",
    "**.c",
    "**.h",
  })